Admin.create!(email:ENV['ADMIN_EMAIL'],password:ENV['ADMIN_PASSWORD'])
DroppedLetter.create!(body:"テスト１")
DroppedLetter.create!(body:"テスト２")
DroppedLetter.create!(body:"テスト３")
DroppedLetter.create!(body:"テスト４")
DroppedLetter.create!(body:"テスト５")
DroppedLetter.create!(body:"テスト６")
DroppedLetter.create!(body:"非表示１", delete_flg:true)
DroppedLetter.create!(body:"非表示２", delete_flg:true)
DroppedLetter.create!(body:"非表示３", delete_flg:true)
DroppedLetter.create!(body:"非表示４", delete_flg:true)